-- ============================================================
--  CONFIGURAÇÃO DO BANCO NO SUPABASE
-- ============================================================
--  1) Acesse supabase.com e crie um projeto (grátis).
--  2) No painel, abra "SQL Editor".
--  3) Cole este arquivo inteiro e execute (Run).
--
--  Este script é SEGURO de rodar de novo: se a tabela ou as
--  políticas já existirem, ele não dá erro.
--
--  Observação: as imagens são guardadas direto na tabela
--  (em base64), então NÃO é preciso criar bucket no Storage.
-- ============================================================


-- CRIANDO A TABELA DE ATIVIDADES (a coluna imagem guarda o base64)
CREATE TABLE IF NOT EXISTS public.atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eixo TEXT NOT NULL,
    numero_eixo INTEGER NOT NULL,
    data DATE NOT NULL,
    nome TEXT NOT NULL,
    imagem TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CRIANDO AS POLÍTICAS DE ACESSO (só se ainda não existirem)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades'
          AND policyname = 'anon pode ler atividades'
    ) THEN
        CREATE POLICY "anon pode ler atividades"
            ON public.atividades FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades'
          AND policyname = 'anon pode cadastrar atividades'
    ) THEN
        CREATE POLICY "anon pode cadastrar atividades"
            ON public.atividades FOR INSERT
            TO anon
            WITH CHECK (true);
    END IF;
END $$;

-- GARANTE QUE A LEITURA PÚBLICA ESTÁ ATIVA
ALTER TABLE public.atividades ENABLE ROW LEVEL SECURITY;

-- MOSTRA O QUE JÁ TEMOS (pode rodar sem problema)
SELECT * FROM public.atividades;