-- ============================================================
--  CONFIGURAÇÃO DO BANCO NO SUPABASE
-- ============================================================
--  1) Acesse supabase.com e crie um projeto (grátis).
--  2) No painel, abra "SQL Editor" e cole este arquivo inteiro.
--  3) Execute (Run).
--  4) Crie o bucket de imagens ("Storage") chamado:
--     atividades-imagens   (marcar como bucket PÚBLICO)
--  5) Rode na aba "SQL Editor" a segunda parte (política do Storage).
-- ============================================================


-- CRIANDO A TABELA DE ATIVIDADES
CREATE TABLE public.atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eixo TEXT NOT NULL,
    numero_eixo INTEGER NOT NULL,
    data DATE NOT NULL,
    nome TEXT NOT NULL,
    imagem TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LIBERA A LEITURA PÚBLICA (anon)
CREATE POLICY "anon pode ler atividades"
    ON public.atividades FOR SELECT
    TO anon
    USING (true);

-- LIBERA O CADASTRO PÚBLICO (anon)
CREATE POLICY "anon pode cadastrar atividades"
    ON public.atividades FOR INSERT
    TO anon
    WITH CHECK (true);

ALTER TABLE public.atividades ENABLE ROW LEVEL SECURITY;

SELECT * FROM public.atividades;


-- ============================================================
--  PARTE 2 - EXECUTE DEPOIS DE CRIAR O BUCKET "atividades-imagens"
-- ============================================================

-- LIBERA O ENVIO (UPLOAD) DE IMAGENS NO BUCKET
CREATE POLICY "anon pode enviar imagens"
    ON storage.objects FOR INSERT
    TO anon
    WITH CHECK (bucket_id = 'atividades-imagens');

-- LIBERA A LEITURA DAS IMAGENS DO BUCKET
CREATE POLICY "anon pode ler imagens"
    ON storage.objects FOR SELECT
    TO anon
    USING (bucket_id = 'atividades-imagens');