-- ============================================================
--  CONFIGURAÇÃO DO BANCO NO SUPABASE
-- ============================================================
--  1) Acesse supabase.com e crie um projeto (grátis).
--  2) No painel, abra "SQL Editor".
--  3) Cole este arquivo inteiro e execute (Run).
--
--  Este script é SEGURO de rodar de novo: se a tabela ou as
--  políticas já existirem, ele não dá erro.
--
--  Observação: as imagens são guardadas direto na tabela
--  (em base64), então NÃO é preciso criar bucket no Storage.
-- ============================================================


-- CRIANDO A TABELA DE ATIVIDADES (a coluna imagem guarda o base64)
CREATE TABLE IF NOT EXISTS public.atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eixo TEXT NOT NULL,
    numero_eixo INTEGER NOT NULL,
    data DATE NOT NULL,
    nome TEXT NOT NULL,
    imagem TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- CRIANDO AS POLÍTICAS DE ACESSO (só se ainda não existirem)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades'
          AND policyname = 'anon pode ler atividades'
    ) THEN
        CREATE POLICY "anon pode ler atividades"
            ON public.atividades FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades'
          AND policyname = 'anon pode cadastrar atividades'
    ) THEN
        CREATE POLICY "anon pode cadastrar atividades"
            ON public.atividades FOR INSERT
            TO anon
            WITH CHECK (true);
    END IF;
END $$;

-- CRIANDO A TABELA DE ATIVIDADES REMOVIDAS
-- Guarda quais cartões fixos do HTML o usuário removeu,
-- para a remoção valer em TODOS os dispositivos.
CREATE TABLE IF NOT EXISTS public.atividades_removidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eixo TEXT NOT NULL,
    titulo TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (eixo, titulo)
);

-- POLÍTICAS DE ACESSO PARA ATIVIDADES REMOVIDAS
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades_removidas'
          AND policyname = 'anon pode ler atividades removidas'
    ) THEN
        CREATE POLICY "anon pode ler atividades removidas"
            ON public.atividades_removidas FOR SELECT
            TO anon
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'atividades_removidas'
          AND policyname = 'anon pode registrar atividades removidas'
    ) THEN
        CREATE POLICY "anon pode registrar atividades removidas"
            ON public.atividades_removidas FOR INSERT
            TO anon
            WITH CHECK (true);
    END IF;
END $$;

-- GARANTE QUE A LEITURA PÚBLICA ESTÁ ATIVA
ALTER TABLE public.atividades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.atividades_removidas ENABLE ROW LEVEL SECURITY;

-- HABILITA TEMPO REAL (websocket) PARA AS DUAS TABELAS
-- Usa DO + IF NOT EXISTS porque o comando de publicação
-- não aceita "IF EXISTS". Seguro de rodar de novo.
DO $$
BEGIN
    -- Garante que a publicação de tempo real existe
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
    ) THEN
        CREATE PUBLICATION supabase_realtime;
    END IF;

    -- Adiciona as tabelas somente se ainda não estiverem na publicação
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'atividades'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.atividades;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'atividades_removidas'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.atividades_removidas;
    END IF;
END $$;

-- MOSTRA O QUE JÁ TEMOS (pode rodar sem problema)
SELECT * FROM public.atividades;
SELECT * FROM public.atividades_removidas;